IMPORTANTO LIBRERIA NUMPY

In [1]:
import numpy as np
import random as rd


Creando una lista de 10 elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Trasfromando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Corroborando el tipo de estructura

In [4]:
type(arreglo)

numpy.ndarray

Corroborando el tipo de datos del arreglo

In [5]:
arreglo.dtype

dtype('int32')

Definiendo el Array de int32 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Sigue siendo un array de int32



In [9]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Transformando los datos de int32 a float32

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

Tambien existe una funcion similar a range pero ocupando Arrays

In [7]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arreglo de 2 en 2 utilizando Arange

In [10]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

ALGUNAS FUNCIONES DE NUMPY

Obteniendo el promedio del array


In [11]:
promedio = np.mean(arreglo)
promedio

5.5

Obteniendo la mediana del array

In [12]:
mediana = np.median(arreglo)
mediana

5.5

Desviación Estandar del arreglo

In [13]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

Obtener la dimension de un arreglo

In [14]:
np.shape(arreglo)

(10,)

Obteniendo el promedio en array


In [15]:
promedio = np.mean (arreglo)
promedio

5.5

Sacar la mediana

Generación de un arreglo de 10 elementos de solo unos

In [18]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
mediana = np.median (arreglo)
mediana

5.5

Transformando el arreglo de unos de punto flotante a enteros

In [19]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Desviacion estandar del arreglo

In [17]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

Generacion de un arreglo de 10 elementos de solo unos

In [16]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Trasformando el arreglo de unos puntos flotantes a enteros

In [18]:
arreglo_int_unos = arreglo_de_unos.astype(int)
arreglo_int_unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Arreglo para crear una lista de ceros

In [19]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

UTILIZANDO LA FUNCION RANDOM

Generando una lista de numeros aleatorios

In [21]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.0921722 , 0.02034071, 0.19849003, 0.05973936, 0.49008049])

Generando una matriz aleatoria de 3x3

In [23]:
matriz = np.random.rand(3,3)
matriz

array([[0.65267391, 0.18117231, 0.85018051],
       [0.74238409, 0.76858363, 0.55161544],
       [0.11688973, 0.06561637, 0.7629111 ]])

Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5

In [24]:
arreglo_aleatorio2 = np.random.randint(1,100,10)
arreglo_aleatorio2

array([46, 85, 45, 76, 64, 95,  9, 46, 22, 32])

Generandp una matriz aleatoria de 10 numeros enteros del 1 al 100

In [26]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[15, 57, 94, 56, 48, 26, 18, 21,  7, 77, 45, 84, 16, 99, 25],
       [35, 15, 86, 25, 45, 81, 28, 35, 84, 83, 68, 18,  7, 54, 13],
       [39, 48, 63, 81, 72, 92, 99, 19, 91, 91, 99, 50, 13, 72, 69],
       [94,  4, 54, 26, 59, 12, 21, 68, 47, 33, 12, 94, 86, 73, 53],
       [40, 29, 95, 92, 28, 47, 15, 35, 94, 43,  9, 77, 76, 56, 49],
       [67, 98, 53, 51, 85, 71, 94, 93, 91, 61, 51, 82, 70, 96, 90],
       [52, 41, 54, 57, 95,  9, 57,  5, 44, 84, 53, 81, 39, 81, 37],
       [68,  8, 45, 92, 83, 96, 98, 75, 45, 18, 58,  5, 94, 85, 96],
       [ 9, 38, 51, 14, 55, 53, 82,  8, 37, 36, 54, 37, 63, 83, 45],
       [13,  8, 26, 68,  5, 87, 35, 30, 82, 70, 60, 68, 42, 13, 42],
       [48, 94, 73, 25,  2, 39, 96, 12, 13, 56, 33, 93,  2, 47, 46],
       [43, 47, 43, 88, 64, 96, 59, 59, 42, 16, 37,  8,  3, 55, 85],
       [34, 97, 86, 26, 11,  1, 60, 61, 18, 93, 83, 48, 32, 84, 84],
       [96,  4, 37, 57, 46, 94,  5, 31, 38, 60, 75, 40, 19, 54, 19],
       [16, 86, 67, 79, 83, 80, 59