DIMENSIONES

In [1]:
import numpy as np

Generando un Array de 12 elementos enteros con Random

In [2]:
arreglo = np.random.randint(1,10,12)
arreglo

array([7, 1, 5, 7, 3, 7, 4, 4, 1, 6, 8, 1])

Obtener la dimensión de un arreglo

In [3]:
np.shape(arreglo)

(12,)

Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

In [4]:
matriz = arreglo.reshape(4,3)
matriz

array([[7, 1, 5],
       [7, 3, 7],
       [4, 4, 1],
       [6, 8, 1]])

Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

In [5]:
np.shape(matriz)

(4, 3)

Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape

In [6]:
matriz = arreglo.reshape(3,4)
matriz

array([[7, 1, 5, 7],
       [3, 7, 4, 4],
       [1, 6, 8, 1]])

Creando un tensor

In [7]:
t = [[[[1,2,3]]]],[[[[4,5,6]]]],[[[[7,8,9]]]],[[[[1,2,3]]]]
t

([[[[1, 2, 3]]]], [[[[4, 5, 6]]]], [[[[7, 8, 9]]]], [[[[1, 2, 3]]]])